package it.cri.demo.ui.dialogs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.AssociativeFee;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.VolunteerService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AssociativeFeeForm extends JDialog {
    private JTextField yearField;
    private JPanel mainPanel;
    private JTextField committeeField;
    private JButton insertButton;
    private JButton cancelButton;
    private JLabel yearLabel;
    private JLabel committeeLabel;
    private JSeparator separator;

    private Volunteer volunteer;
    private VolunteerService volunteerService;

    public AssociativeFeeForm(Frame owner, Volunteer volunteer, VolunteerService volunteerService) {
        super(owner, "Inserisci quota associativa", true);
        setContentPane(mainPanel);
        setSize(160, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.volunteer = volunteer;
        this.volunteerService = volunteerService;
        cancelButton.addActionListener(e -> dispose());
        insertButton.addActionListener(e -> confirmSave());

    }

    private void confirmSave() {
        int year = Integer.parseInt(yearField.getText());
        String committee = committeeField.getText();

        AssociativeFee a = new AssociativeFee();
        a.setYear(year);
        a.setCommittee(committee);
        a.setVolunteer(this.volunteer);

        this.volunteer.getAssociativeFees().add(a);
        this.volunteerService.save(volunteer);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,fill:max(d;4px):grow", "fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:d:grow,center:max(d;4px):noGrow"));
        yearField = new JTextField();
        yearField.setPreferredSize(new Dimension(160, 30));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(yearField, cc.xyw(1, 2, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        yearLabel = new JLabel();
        yearLabel.setPreferredSize(new Dimension(160, 17));
        yearLabel.setText("Anno");
        mainPanel.add(yearLabel, cc.xyw(1, 1, 2));
        committeeField = new JTextField();
        committeeField.setMinimumSize(new Dimension(160, 30));
        mainPanel.add(committeeField, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        committeeLabel = new JLabel();
        committeeLabel.setPreferredSize(new Dimension(160, 17));
        committeeLabel.setText("Comitato");
        mainPanel.add(committeeLabel, cc.xyw(1, 3, 2));
        separator = new JSeparator();
        mainPanel.add(separator, cc.xyw(1, 5, 2, CellConstraints.FILL, CellConstraints.FILL));
        insertButton = new JButton();
        insertButton.setMaximumSize(new Dimension(85, 30));
        insertButton.setMinimumSize(new Dimension(70, 30));
        insertButton.setPreferredSize(new Dimension(80, 30));
        insertButton.setText("Inserisci");
        mainPanel.add(insertButton, cc.xy(1, 6));
        cancelButton = new JButton();
        cancelButton.setMaximumSize(new Dimension(85, 30));
        cancelButton.setMinimumSize(new Dimension(70, 30));
        cancelButton.setPreferredSize(new Dimension(80, 30));
        cancelButton.setText("Annulla");
        mainPanel.add(cancelButton, cc.xy(2, 6));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
