package it.cri.demo.ui.dialogs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Recall;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.VolunteerService;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class RecallForm extends JDialog {
    private JPanel mainPanel;
    private JFormattedTextField startDateFormattedField;
    private JFormattedTextField endDateFormattedField;
    private JTextField activityField;
    private JLabel startDateLabel;
    private JLabel endDateLabel;
    private JLabel activityLabel;
    private JButton insertButton;
    private JButton cancelButton;
    private JSeparator separator;

    private Volunteer volunteer;
    private VolunteerService volunteerService;

    public RecallForm(Frame owner, Volunteer volunteer, VolunteerService volunteerService) {
        super(owner, "Inserisci richiamo", true);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(160, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.volunteer = volunteer;
        this.volunteerService = volunteerService;
        cancelButton.addActionListener(e -> dispose());
        insertButton.addActionListener(e -> confirmSave());
    }

    private void confirmSave() {
        LocalDate startDate = LocalDate.parse(startDateFormattedField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate endDate = LocalDate.parse(endDateFormattedField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String activity = activityField.getText();

        Recall r = new Recall();
        r.setStartDate(startDate);
        r.setEndDate(endDate);
        r.setActivity(activity);
        r.setVolunteer(this.volunteer);

        this.volunteer.getRecalls().add(r);
        this.volunteerService.save(this.volunteer);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):grow,fill:max(d;4px):grow", "fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:d:grow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(startDateFormattedField, cc.xyw(1, 2, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        startDateLabel = new JLabel();
        startDateLabel.setText("Data inizio");
        mainPanel.add(startDateLabel, cc.xyw(1, 1, 2));
        mainPanel.add(endDateFormattedField, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        endDateLabel = new JLabel();
        endDateLabel.setText("Data fine");
        mainPanel.add(endDateLabel, cc.xyw(1, 3, 2));
        activityField = new JTextField();
        mainPanel.add(activityField, cc.xyw(1, 6, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        activityLabel = new JLabel();
        activityLabel.setText("Attività");
        mainPanel.add(activityLabel, cc.xyw(1, 5, 2));
        separator = new JSeparator();
        mainPanel.add(separator, cc.xyw(1, 7, 2, CellConstraints.FILL, CellConstraints.FILL));
        insertButton = new JButton();
        insertButton.setText("Inserisci");
        mainPanel.add(insertButton, cc.xy(1, 8));
        cancelButton = new JButton();
        cancelButton.setText("Annulla");
        mainPanel.add(cancelButton, cc.xy(2, 8));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        MaskFormatter dateFormatter = null;
        try {
            dateFormatter = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        dateFormatter.setPlaceholderCharacter('_');

        startDateFormattedField = new JFormattedTextField(dateFormatter);
        startDateFormattedField.setColumns(10);

        endDateFormattedField = new JFormattedTextField(dateFormatter);
        endDateFormattedField.setColumns(10);
    }
}
