package it.cri.demo.ui.insertdialogs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Brevet;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.BrevetService;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class BrevetForm extends JDialog {
    private JFormattedTextField dateFormattedField;
    private JPanel mainPanel;
    private JLabel dateLabel;
    private JTextField doctorField;
    private JLabel doctorLabel;
    private JButton insertButton;
    private JButton cancelButton;

    private Volunteer volunteer;
    private BrevetService brevetService;

    public BrevetForm(Frame owner, Volunteer volunteer, BrevetService brevetService) {
        super(owner, "Inserisci brevetto", true);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(160, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.volunteer = volunteer;
        this.brevetService = brevetService;
        cancelButton.addActionListener(e -> dispose());
        insertButton.addActionListener(e -> confirmSave());
    }

    private void confirmSave() {
        //TODO: dateFormattedField.getText() or dateFormattedField.getValue()?
        LocalDate date = LocalDate.parse(dateFormattedField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String doctor = doctorField.getText();

        Brevet b = new Brevet();
        b.setDate(date);
        b.setDoctor(doctor);
        b.setVolunteer(this.volunteer);

        this.brevetService.save(b);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,fill:max(d;4px):grow", "fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):grow,center:max(d;4px):noGrow"));
        dateFormattedField.setPreferredSize(new Dimension(160, 30));
        dateFormattedField.setText("");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(dateFormattedField, cc.xyw(1, 2, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        dateLabel = new JLabel();
        dateLabel.setPreferredSize(new Dimension(160, 17));
        dateLabel.setText("Data");
        mainPanel.add(dateLabel, cc.xyw(1, 1, 2));
        doctorField = new JTextField();
        doctorField.setPreferredSize(new Dimension(160, 30));
        mainPanel.add(doctorField, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        doctorLabel = new JLabel();
        doctorLabel.setPreferredSize(new Dimension(160, 17));
        doctorLabel.setText("Dottore");
        mainPanel.add(doctorLabel, cc.xyw(1, 3, 2));
        final JSeparator separator1 = new JSeparator();
        mainPanel.add(separator1, cc.xyw(1, 5, 2, CellConstraints.FILL, CellConstraints.FILL));
        insertButton = new JButton();
        insertButton.setPreferredSize(new Dimension(80, 30));
        insertButton.setText("Inserisci");
        mainPanel.add(insertButton, cc.xy(1, 6));
        cancelButton = new JButton();
        cancelButton.setPreferredSize(new Dimension(80, 30));
        cancelButton.setText("Annulla");
        mainPanel.add(cancelButton, cc.xy(2, 6));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        MaskFormatter dateFormatter = null;
        try {
            dateFormatter = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        dateFormatter.setPlaceholderCharacter('_');

        dateFormattedField = new JFormattedTextField(dateFormatter);
        dateFormattedField.setColumns(10);
    }
}
