package it.cri.demo.ui.insertdialogs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Promotion;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.PromotionService;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class PromotionForm extends JDialog {
    private JPanel mainPanel;
    private JFormattedTextField dateFormattedField;
    private JTextField degreeField;
    private JButton insertButton;
    private JButton cancelButton;
    private JLabel dateLabel;
    private JLabel degreeLabel;
    private JSeparator separator;

    private Volunteer volunteer;
    private PromotionService promotionService;

    public PromotionForm(Frame owner, Volunteer volunteer, PromotionService promotionService) {
        super(owner, "Inserisci promozione", true);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(160, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.volunteer = volunteer;
        this.promotionService = promotionService;
        cancelButton.addActionListener(e -> dispose());
        insertButton.addActionListener(e -> confirmSave());
    }

    private void confirmSave() {
        //TODO: dateFormattedField.getText() or dateFormattedField.getValue()?
        LocalDate date = LocalDate.parse(dateFormattedField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String degree = degreeField.getText();

        Promotion p = new Promotion();
        p.setDate(date);
        p.setDegree(degree);
        p.setVolunteer(this.volunteer);

        this.promotionService.save(p);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):grow,fill:max(d;4px):grow", "fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:d:grow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(dateFormattedField, cc.xyw(1, 2, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        dateLabel = new JLabel();
        dateLabel.setText("Data");
        mainPanel.add(dateLabel, cc.xyw(1, 1, 2));
        degreeField = new JTextField();
        mainPanel.add(degreeField, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        degreeLabel = new JLabel();
        degreeLabel.setText("Grado");
        mainPanel.add(degreeLabel, cc.xyw(1, 3, 2));
        separator = new JSeparator();
        mainPanel.add(separator, cc.xyw(1, 5, 2, CellConstraints.FILL, CellConstraints.FILL));
        insertButton = new JButton();
        insertButton.setText("Inserisci");
        mainPanel.add(insertButton, cc.xy(1, 6));
        cancelButton = new JButton();
        cancelButton.setText("Annulla");
        mainPanel.add(cancelButton, cc.xy(2, 6));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        MaskFormatter dateFormatter = null;
        try {
            dateFormatter = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        dateFormatter.setPlaceholderCharacter('_');

        dateFormattedField = new JFormattedTextField(dateFormatter);
        dateFormattedField.setColumns(10);
    }
}
