package it.cri.demo.ui.insertdialogs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Qualification;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.QualificationService;

import javax.swing.*;
import java.awt.*;

public class QualificationForm extends JDialog {
    private JTextField typeField;
    private JPanel mainPanel;
    private JLabel typeLabel;
    private JTextField committeeField;
    private JLabel committeeLabel;
    private JButton insertButton;
    private JButton cancelButton;

    private Volunteer volunteer;
    private QualificationService qualificationService;

    public QualificationForm(Frame owner, Volunteer volunteer, QualificationService qualificationService) {
        super(owner, "Inserisci qualifica", true);
        setContentPane(mainPanel);
        setSize(160, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.volunteer = volunteer;
        this.qualificationService = qualificationService;


        cancelButton.addActionListener(e -> dispose());
        insertButton.addActionListener(e -> confirmSave());
    }

    private void confirmSave() {
        String type = typeField.getText();
        String committee = committeeField.getText();

        Qualification q = new Qualification();
        q.setType(type);
        q.setCommittee(committee);
        q.setVolunteer(this.volunteer);

        this.qualificationService.save(q);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):grow,fill:max(d;4px):grow", "fill:max(d;4px):noGrow,center:d:noGrow,fill:max(d;4px):noGrow,center:d:noGrow,center:d:grow,center:max(d;4px):noGrow"));
        typeField = new JTextField();
        typeField.setPreferredSize(new Dimension(160, 30));
        typeField.setText("");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(typeField, cc.xyw(1, 2, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        typeLabel = new JLabel();
        typeLabel.setPreferredSize(new Dimension(160, 17));
        typeLabel.setText("Tipo");
        mainPanel.add(typeLabel, cc.xyw(1, 1, 2));
        committeeField = new JTextField();
        committeeField.setPreferredSize(new Dimension(160, 30));
        mainPanel.add(committeeField, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        committeeLabel = new JLabel();
        committeeLabel.setPreferredSize(new Dimension(160, 17));
        committeeLabel.setText("Comitato");
        mainPanel.add(committeeLabel, cc.xyw(1, 3, 2));
        final JSeparator separator1 = new JSeparator();
        mainPanel.add(separator1, cc.xyw(1, 5, 2, CellConstraints.FILL, CellConstraints.FILL));
        insertButton = new JButton();
        insertButton.setPreferredSize(new Dimension(80, 30));
        insertButton.setText("Inserisci");
        mainPanel.add(insertButton, cc.xy(1, 6));
        cancelButton = new JButton();
        cancelButton.setPreferredSize(new Dimension(80, 30));
        cancelButton.setText("Annulla");
        mainPanel.add(cancelButton, cc.xy(2, 6));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
