package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.AssociativeFeeTableModel;
import it.cri.demo.entity.AssociativeFee;
import it.cri.demo.entity.MedicalVisit;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.AssociativeFeeService;
import it.cri.demo.ui.detaildialogs.AssociativeFeeDetails;
import it.cri.demo.ui.detaildialogs.MedicalVisitDetails;
import it.cri.demo.ui.insertdialogs.AssociativeFeeForm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

public class AssociativeFeeUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JLabel label;
    private JScrollPane scrollPane;
    private JButton insertButton;

    private final List<AssociativeFee> associativeFeeList;

    public AssociativeFeeUI(Frame owner, Volunteer volunteer, AssociativeFeeService associativeFeeService) {
        super(owner, "Quote associative", true);
        this.associativeFeeList = associativeFeeService.getAllByVolunteer(volunteer);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        insertButton.addActionListener(e -> new AssociativeFeeForm(null, volunteer, associativeFeeService).setVisible(true));

        table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // We are looking for a double-click
                if (e.getClickCount() == 2) {
                    int viewRow = table1.getSelectedRow();
                    if (viewRow != -1) {
                        // 1. Convert the view row index to the model row index
                        int modelRow = table1.convertRowIndexToModel(viewRow);

                        // 2. Retrieve the selected object
                        AssociativeFee selectedRecord = associativeFeeList.get(modelRow);

                        // 3. Open the detail dialog
                        new AssociativeFeeDetails((Frame) getOwner(), selectedRecord, associativeFeeService).setVisible(true);
                    }
                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,center:max(d;100px):grow,center:max(d;4px):noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Quote associative");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        insertButton = new JButton();
        insertButton.setText("Inserisci nuova quota associativa");
        mainPanel.add(insertButton, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new AssociativeFeeTableModel(this.associativeFeeList));
    }
}
