package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.AssociativeFeeTableModel;
import it.cri.demo.entity.AssociativeFee;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.VolunteerService;
import it.cri.demo.ui.dialogs.AssociativeFeeForm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class AssociativeFeeUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JLabel label;
    private JScrollPane scrollPane;
    private JButton insertButton;

    private final List<AssociativeFee> associativeFeeList;

    public AssociativeFeeUI(Frame owner, Volunteer volunteer, VolunteerService volunteerService) {
        super(owner, "Quote associative", true);
        this.associativeFeeList = volunteer.getAssociativeFees();
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        insertButton.addActionListener(e -> new AssociativeFeeForm(null, volunteer, volunteerService).setVisible(true));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,center:max(d;100px):grow,center:max(d;4px):noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Quote associative");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        insertButton = new JButton();
        insertButton.setText("Inserisci nuova quota associativa");
        mainPanel.add(insertButton, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new AssociativeFeeTableModel(this.associativeFeeList));
    }
}
