package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

public class ExtendedDetails {
    private JTabbedPane tabbedPane;
    private JPanel panel1;
    private JPanel tab1;
    private JPanel tab2;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:58px:grow"));
        tabbedPane = new JTabbedPane();
        CellConstraints cc = new CellConstraints();
        panel1.add(tabbedPane, cc.xy(1, 1));
        tab1 = new JPanel();
        tab1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        tabbedPane.addTab("Ciao", tab1);
        final JLabel label1 = new JLabel();
        label1.setText("LABEL 1");
        tab1.add(label1, cc.xy(1, 1));
        tab2 = new JPanel();
        tab2.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        tabbedPane.addTab("Untitled", tab2);
        final JLabel label2 = new JLabel();
        label2.setText("PROVA");
        tab2.add(label2, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
