package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.*;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class FormTest extends JFrame {
    private JPanel panel1;
    private JList<Volunteer> list1;
    private DefaultListModel<Volunteer> listModel;
    private JScrollPane scrollPane;
    private JButton insertButton;
    private JButton refreshButton;

    private final VolunteerService volunteerService;
    private final AssociativeFeeService associativeFeeService;
    private final BrevetService brevetService;
    private final MedicalVisitService medicalVisitService;
    private final PromotionService promotionService;
    private final QualificationService qualificationService;
    private final RecallService recallService;

    public FormTest(VolunteerService volunteerService,
                    AssociativeFeeService associativeFeeService,
                    BrevetService brevetService,
                    MedicalVisitService medicalVisitService,
                    PromotionService promotionService,
                    QualificationService qualificationService,
                    RecallService recallService) throws HeadlessException {

        this.volunteerService = volunteerService;
        this.associativeFeeService = associativeFeeService;
        this.brevetService = brevetService;
        this.medicalVisitService = medicalVisitService;
        this.promotionService = promotionService;
        this.qualificationService = qualificationService;
        this.recallService = recallService;

        setContentPane(panel1);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("GUI Test");
        setSize(800, 500);

        listModel = new DefaultListModel<>();
        list1.setModel(listModel);

        updateListWiew();

        list1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Volunteer volunteer = list1.getSelectedValue();
                    showVolunteerDialog(volunteer);
                }
            }
        });

        insertButton.addActionListener(e -> showInsertDialog());
        refreshButton.addActionListener(e -> updateListWiew());

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ignored) {
        }
    }

    private void showInsertDialog() {
        new VolunteerInsert(this, volunteerService).setVisible(true);
    }

    private void updateListWiew() {
        listModel.removeAllElements();
        listModel.addAll(volunteerService.getAll());
    }

    private void showVolunteerDialog(Volunteer v) {
        new VolunteerDetails(this, v,
                this.volunteerService,
                this.associativeFeeService,
                this.brevetService,
                this.medicalVisitService,
                this.promotionService,
                this.qualificationService,
                this.recallService).setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:341px:grow,center:34px:noGrow,center:max(d;4px):noGrow"));
        panel1.setPreferredSize(new Dimension(800, 400));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Lista arruolati", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        panel1.add(scrollPane, cc.xyw(1, 1, 2, CellConstraints.FILL, CellConstraints.FILL));
        list1 = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        list1.setModel(defaultListModel1);
        scrollPane.setViewportView(list1);
        insertButton = new JButton();
        insertButton.setText("Inserisci nuovo arruolato");
        panel1.add(insertButton, cc.xy(1, 2));
        refreshButton = new JButton();
        refreshButton.setText("Aggiorna lista");
        panel1.add(refreshButton, cc.xy(1, 3));
        try {
            System.out.println(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
