package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.MedicalVisitTableModel;
import it.cri.demo.entity.MedicalVisit;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.MedicalVisitService;
import it.cri.demo.ui.dialogs.MedicalVisitForm;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class MedicalVisitUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JScrollPane scrollPane;
    private JLabel label;
    private JButton insertButton;

    private final List<MedicalVisit> medicalVisitList;

    public MedicalVisitUI(Frame owner, Volunteer volunteer, MedicalVisitService medicalVisitService) throws HeadlessException {
        super(owner, "Medical visit", true);
        this.medicalVisitList = medicalVisitService.getAllByVolunteer(volunteer);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        insertButton.addActionListener(e -> new MedicalVisitForm(null, volunteer, medicalVisitService).setVisible(true));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("center:d:grow", "center:max(d;4px):noGrow,center:max(d;100px):grow,center:max(d;4px):noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Visite mediche");
        mainPanel.add(label, cc.xy(1, 1));
        insertButton = new JButton();
        insertButton.setText("Inserisci nuova visita medica");
        mainPanel.add(insertButton, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new MedicalVisitTableModel(this.medicalVisitList));
    }
}
