package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.MedicalVisitTableModel;
import it.cri.demo.entity.MedicalVisit;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.MedicalVisitService;
import it.cri.demo.service.VolunteerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class MedicalVisitUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JScrollPane scrollPane;
    private JLabel label;

    private final List<MedicalVisit> medicalVisitList;

    public MedicalVisitUI(Frame owner, Volunteer volunteer, VolunteerService volunteerService) throws HeadlessException {
        super(owner, "Medical visit", true);
        this.medicalVisitList = volunteer.getMedicalVisits();
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
//        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("center:d:grow", "center:18px:noGrow,center:d:grow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Visite mediche");
        mainPanel.add(label, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new MedicalVisitTableModel(this.medicalVisitList));
    }
}
