package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.PromotionTableModel;
import it.cri.demo.entity.Promotion;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class PromotionUI extends JDialog {
    private JPanel mainPanel;
    private JScrollPane scrollPane;
    private JTable table1;
    private JLabel label;

    private final List<Promotion> promotionList;

    public PromotionUI(Frame owner, List<Promotion> promotionList) {
        super(owner, "Promozioni e gradi", true);
        this.promotionList = promotionList;
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Promozioni e gradi");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new PromotionTableModel(this.promotionList));
    }
}
