package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.QualificationTableModel;
import it.cri.demo.entity.Qualification;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.QualificationService;
import it.cri.demo.ui.insertdialogs.QualificationForm;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class QualificationUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JLabel label;
    private JScrollPane scrollPane;
    private JButton insertButton;
    private final List<Qualification> qualificationList;

    public QualificationUI(Frame owner, Volunteer volunteer, QualificationService qualificationService) {
        super(owner, "Qualifiche", true);
        this.qualificationList = qualificationService.getAllByVolunteer(volunteer);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        insertButton.addActionListener(e -> new QualificationForm(null, volunteer, qualificationService).setVisible(true));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,center:max(d;100px):grow,center:max(d;4px):noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Qualifiche");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        insertButton = new JButton();
        insertButton.setText("Inserisci nuova qualifica");
        mainPanel.add(insertButton, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new QualificationTableModel(this.qualificationList));
    }
}
