package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.RecallTableModel;
import it.cri.demo.entity.Recall;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class RecallUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JScrollPane scrollPane;
    private JLabel label;

    private final List<Recall> recallList;

    public RecallUI(Frame owner, List<Recall> recallList) {
        super(owner, "Richiami", true);
        this.recallList = recallList;
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,center:d:noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xyw(1, 2, 3, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Richiami");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new RecallTableModel(this.recallList));
    }
}
