package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.controller.RecallTableModel;
import it.cri.demo.entity.Brevet;
import it.cri.demo.entity.Recall;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.RecallService;
import it.cri.demo.ui.detaildialogs.BrevetDetails;
import it.cri.demo.ui.detaildialogs.RecallDetails;
import it.cri.demo.ui.insertdialogs.RecallForm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

public class RecallUI extends JDialog {
    private JPanel mainPanel;
    private JTable table1;
    private JScrollPane scrollPane;
    private JLabel label;
    private JButton insertButton;

    private final List<Recall> recallList;

    public RecallUI(Frame owner, Volunteer volunteer, RecallService recallService) {
        super(owner, "Richiami", true);
        this.recallList = recallService.getAllByVolunteer(volunteer);
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(800, 500);
        insertButton.addActionListener(e -> new RecallForm(null, volunteer, recallService).setVisible(true));

        table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // We are looking for a double-click
                if (e.getClickCount() == 2) {
                    int viewRow = table1.getSelectedRow();
                    if (viewRow != -1) {
                        // 1. Convert the view row index to the model row index
                        int modelRow = table1.convertRowIndexToModel(viewRow);

                        // 2. Retrieve the selected object
                        Recall selectedRecord = recallList.get(modelRow);

                        // 3. Open the detail dialog
                        new RecallDetails((Frame) getOwner(), selectedRecord, recallService).setVisible(true);
                    }
                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,center:max(d;100px):grow,center:max(d;4px):noGrow"));
        scrollPane = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(scrollPane, cc.xyw(1, 2, 3, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane.setViewportView(table1);
        label = new JLabel();
        label.setText("Richiami");
        mainPanel.add(label, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        insertButton = new JButton();
        insertButton.setText("Inserisci nuovo richiamo");
        mainPanel.add(insertButton, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(new RecallTableModel(this.recallList));
    }
}
