package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.VolunteerService;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class VolunteerInsert extends JDialog {
    private JPanel detailPanel;
    private JTextField nameField;
    private JTextField surnameField;
    private JTextField birthDateField;
    private JTextField birthPlaceField;
    private JTextField phoneField;
    private JTextField emailField;
    private JTextField residenceField;
    private JTextField registrationNumberField;
    private JTextField feeField;
    private JTextField rankField;
    private JTextField lastRecallField;
    private JTextField activityField;
    private JTextField lastVisitField;
    private JTextField nextVisitField;
    private JLabel nameLabel;
    private JLabel surnameLabel;
    private JLabel birthDateLabel;
    private JLabel birthPlaceLabel;
    private JLabel phoneLabel;
    private JLabel emailLabel;
    private JLabel residenceLabel;
    private JLabel registrationNumberLabel;
    private JLabel feeLabel;
    private JLabel rankLabel;
    private JLabel lastRecallLabel;
    private JLabel activityLabel;
    private JLabel lastVisitLabel;
    private JLabel nextVisitLabel;
    private JButton saveButton;
    private JButton cancelButton;
    private final VolunteerService service;


    public VolunteerInsert(Frame owner, VolunteerService service) throws HeadlessException {
        super(owner, "Nuovo arruolato", false);
        setContentPane(detailPanel);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(800, 500);
        setTitle("Nuovo arruolato");
        setVisible(true);
        this.service = service;

        saveButton.addActionListener(e -> insertVolunteer());
        cancelButton.addActionListener(e -> dispose());
    }

    private void insertVolunteer() {
        Volunteer v = new Volunteer();
        v.setName(nameField.getText());
        v.setSurname(surnameField.getText());
        v.setBirthDate(LocalDate.parse(birthDateField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))); //TODO check format
        v.setBirthPlace(birthPlaceField.getText());
        v.setPhoneNumber(phoneField.getText());
        v.setEmailAddress(emailField.getText());
        v.setResidenceAddress(residenceField.getText());
        v.setRegistrationNumber(registrationNumberField.getText());
        v.setFee(Double.valueOf(feeField.getText()));
        v.setRankValue(rankField.getText());
        v.setLastRecall(LocalDate.parse(lastRecallField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))); //TODO check format
        v.setLastActivity(activityField.getText());
        v.setLastMedicalVisit(LocalDate.parse(lastVisitField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))); //TODO check format
        v.setNextMedicalVisit(LocalDate.parse(nextVisitField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))); //TODO check format
        service.save(v);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        detailPanel = new JPanel();
        detailPanel.setLayout(new FormLayout("fill:d:grow,fill:d:grow", "fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:14px:noGrow,fill:max(d;4px):noGrow,fill:34px:noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:30px:noGrow,fill:max(d;4px):noGrow,fill:32px:noGrow,center:max(d;4px):noGrow"));
        detailPanel.setAlignmentX(0.5f);
        detailPanel.setAlignmentY(0.5f);
        detailPanel.setAutoscrolls(true);
        detailPanel.setName("Dettagli arruolato");
        detailPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Dettagli arruolato", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        nameField = new JTextField();
        nameField.setEditable(true);
        nameField.setPreferredSize(new Dimension(100, 30));
        CellConstraints cc = new CellConstraints();
        detailPanel.add(nameField, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.CENTER));
        nameLabel = new JLabel();
        nameLabel.setText("Nome");
        detailPanel.add(nameLabel, cc.xy(1, 1));
        surnameLabel = new JLabel();
        surnameLabel.setText("Cognome");
        detailPanel.add(surnameLabel, cc.xy(2, 1, CellConstraints.LEFT, CellConstraints.DEFAULT));
        surnameField = new JTextField();
        surnameField.setEditable(true);
        surnameField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(surnameField, cc.xy(2, 2, CellConstraints.FILL, CellConstraints.CENTER));
        birthDateField = new JTextField();
        birthDateField.setEditable(true);
        birthDateField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(birthDateField, cc.xy(1, 4, CellConstraints.FILL, CellConstraints.CENTER));
        birthPlaceField = new JTextField();
        birthPlaceField.setEditable(true);
        birthPlaceField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(birthPlaceField, cc.xy(2, 4, CellConstraints.FILL, CellConstraints.CENTER));
        birthDateLabel = new JLabel();
        birthDateLabel.setText("Data di nascita");
        detailPanel.add(birthDateLabel, cc.xy(1, 3));
        birthPlaceLabel = new JLabel();
        birthPlaceLabel.setText("Luogo di nascita");
        detailPanel.add(birthPlaceLabel, cc.xy(2, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        phoneField = new JTextField();
        phoneField.setEditable(true);
        phoneField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(phoneField, cc.xy(1, 6, CellConstraints.FILL, CellConstraints.CENTER));
        emailField = new JTextField();
        emailField.setEditable(true);
        emailField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(emailField, cc.xy(2, 6, CellConstraints.FILL, CellConstraints.CENTER));
        phoneLabel = new JLabel();
        phoneLabel.setText("Cellulare");
        detailPanel.add(phoneLabel, cc.xy(1, 5));
        emailLabel = new JLabel();
        emailLabel.setText("e-mail");
        detailPanel.add(emailLabel, cc.xy(2, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        residenceField = new JTextField();
        residenceField.setEditable(true);
        residenceField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(residenceField, cc.xy(1, 8, CellConstraints.FILL, CellConstraints.CENTER));
        residenceLabel = new JLabel();
        residenceLabel.setText("Residenza");
        detailPanel.add(residenceLabel, cc.xy(1, 7, CellConstraints.LEFT, CellConstraints.FILL));
        final JSeparator separator1 = new JSeparator();
        detailPanel.add(separator1, cc.xy(1, 9, CellConstraints.FILL, CellConstraints.FILL));
        final JSeparator separator2 = new JSeparator();
        detailPanel.add(separator2, cc.xy(2, 9, CellConstraints.FILL, CellConstraints.FILL));
        registrationNumberField = new JTextField();
        registrationNumberField.setEditable(true);
        registrationNumberField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(registrationNumberField, cc.xy(1, 11, CellConstraints.FILL, CellConstraints.CENTER));
        registrationNumberLabel = new JLabel();
        registrationNumberLabel.setText("Num. Matricola");
        detailPanel.add(registrationNumberLabel, cc.xy(1, 10, CellConstraints.LEFT, CellConstraints.DEFAULT));
        feeField = new JTextField();
        feeField.setEditable(true);
        feeField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(feeField, cc.xy(2, 11, CellConstraints.FILL, CellConstraints.CENTER));
        feeLabel = new JLabel();
        feeLabel.setText("Quota ass.");
        detailPanel.add(feeLabel, cc.xy(2, 10, CellConstraints.LEFT, CellConstraints.DEFAULT));
        rankField = new JTextField();
        rankField.setEditable(true);
        rankField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(rankField, cc.xy(1, 13, CellConstraints.FILL, CellConstraints.CENTER));
        rankLabel = new JLabel();
        rankLabel.setText("Grado");
        detailPanel.add(rankLabel, cc.xy(1, 12, CellConstraints.LEFT, CellConstraints.FILL));
        lastRecallField = new JTextField();
        lastRecallField.setEditable(true);
        lastRecallField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(lastRecallField, cc.xy(2, 13, CellConstraints.FILL, CellConstraints.CENTER));
        lastRecallLabel = new JLabel();
        lastRecallLabel.setText("Ultimo richiamo");
        detailPanel.add(lastRecallLabel, cc.xy(2, 12));
        activityField = new JTextField();
        activityField.setEditable(true);
        activityField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(activityField, cc.xy(1, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        activityLabel = new JLabel();
        activityLabel.setText("Attività");
        detailPanel.add(activityLabel, cc.xy(1, 14));
        lastVisitField = new JTextField();
        lastVisitField.setEditable(true);
        lastVisitField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(lastVisitField, cc.xy(1, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        lastVisitLabel = new JLabel();
        lastVisitLabel.setText("Ultima visita");
        detailPanel.add(lastVisitLabel, cc.xy(1, 16));
        nextVisitField = new JTextField();
        nextVisitField.setEditable(true);
        nextVisitField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(nextVisitField, cc.xy(2, 17, CellConstraints.FILL, CellConstraints.CENTER));
        nextVisitLabel = new JLabel();
        nextVisitLabel.setText("Prox. visita");
        detailPanel.add(nextVisitLabel, cc.xy(2, 16));
        saveButton = new JButton();
        saveButton.setText("Salva");
        detailPanel.add(saveButton, cc.xy(1, 18));
        cancelButton = new JButton();
        cancelButton.setText("Annulla");
        detailPanel.add(cancelButton, cc.xy(2, 18));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return detailPanel;
    }

}