package it.cri.demo.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.cri.demo.entity.Volunteer;
import it.cri.demo.service.VolunteerService;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class VolunteerInsert extends JDialog {
    private JPanel detailPanel;
    private JTextField nameField;
    private JTextField surnameField;
    private JFormattedTextField birthDateField;
    private JTextField birthPlaceField;
    private JTextField phoneField;
    private JTextField emailField;
    private JTextField residenceField;
    private JTextField registrationNumberField;
    private JLabel nameLabel;
    private JLabel surnameLabel;
    private JLabel birthDateLabel;
    private JLabel birthPlaceLabel;
    private JLabel emailLabel;
    private JLabel phoneLabel;
    private JLabel registrationNumberLabel;
    private JButton saveButton;
    private JButton cancelButton;
    private JTextField pecField;
    private JLabel pecLabel;
    private JLabel residenceLabel;
    private final VolunteerService service;


    public VolunteerInsert(Frame owner, VolunteerService service) throws HeadlessException {
        super(owner, "Nuovo arruolato", false);
        $$$setupUI$$$();
        setContentPane(detailPanel);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(400, 300);
        setTitle("Nuovo arruolato");
        this.service = service;

        saveButton.addActionListener(e -> {
            insertVolunteer();
            dispose();
        });
        cancelButton.addActionListener(e -> dispose());
    }

    private void insertVolunteer() {
        Volunteer v = new Volunteer();
        v.setName(nameField.getText());
        v.setSurname(surnameField.getText());
        v.setBirthDate(LocalDate.parse(birthDateField.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        v.setBirthPlace(birthPlaceField.getText());
        v.setPhoneNumber(phoneField.getText());
        v.setEmailAddress(emailField.getText());
        v.setPecAddress(pecField.getText());
        v.setResidenceAddress(residenceField.getText());
        v.setRegistrationNumber(registrationNumberField.getText());
        service.save(v);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        detailPanel = new JPanel();
        detailPanel.setLayout(new FormLayout("fill:d:grow,fill:d:grow", "fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,fill:max(d;4px):noGrow,center:max(d;4px):noGrow,fill:d:grow,center:max(d;4px):noGrow"));
        detailPanel.setAlignmentX(0.5f);
        detailPanel.setAlignmentY(0.5f);
        detailPanel.setAutoscrolls(true);
        detailPanel.setName("Dettagli arruolato");
        detailPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Dettagli arruolato", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        nameField = new JTextField();
        nameField.setEditable(true);
        nameField.setPreferredSize(new Dimension(100, 30));
        CellConstraints cc = new CellConstraints();
        detailPanel.add(nameField, cc.xy(1, 2, CellConstraints.FILL, CellConstraints.CENTER));
        nameLabel = new JLabel();
        nameLabel.setText("Nome");
        detailPanel.add(nameLabel, cc.xy(1, 1));
        surnameLabel = new JLabel();
        surnameLabel.setText("Cognome");
        detailPanel.add(surnameLabel, cc.xy(2, 1, CellConstraints.LEFT, CellConstraints.DEFAULT));
        surnameField = new JTextField();
        surnameField.setEditable(true);
        surnameField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(surnameField, cc.xy(2, 2, CellConstraints.FILL, CellConstraints.CENTER));
        birthDateField.setEditable(true);
        birthDateField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(birthDateField, cc.xy(1, 4, CellConstraints.FILL, CellConstraints.CENTER));
        birthPlaceField = new JTextField();
        birthPlaceField.setEditable(true);
        birthPlaceField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(birthPlaceField, cc.xy(2, 4, CellConstraints.FILL, CellConstraints.CENTER));
        birthDateLabel = new JLabel();
        birthDateLabel.setText("Data di nascita");
        detailPanel.add(birthDateLabel, cc.xy(1, 3));
        birthPlaceLabel = new JLabel();
        birthPlaceLabel.setText("Luogo di nascita");
        detailPanel.add(birthPlaceLabel, cc.xy(2, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        pecField = new JTextField();
        pecField.setEditable(true);
        pecField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(pecField, cc.xy(1, 6, CellConstraints.FILL, CellConstraints.CENTER));
        emailField = new JTextField();
        emailField.setEditable(true);
        emailField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(emailField, cc.xy(2, 6, CellConstraints.FILL, CellConstraints.CENTER));
        pecLabel = new JLabel();
        pecLabel.setText("PEC");
        detailPanel.add(pecLabel, cc.xy(1, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        emailLabel = new JLabel();
        emailLabel.setText("e-mail");
        detailPanel.add(emailLabel, cc.xy(2, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        phoneField = new JTextField();
        phoneField.setEditable(true);
        phoneField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(phoneField, cc.xy(1, 8, CellConstraints.FILL, CellConstraints.CENTER));
        phoneLabel = new JLabel();
        phoneLabel.setText("Cellulare");
        detailPanel.add(phoneLabel, cc.xy(1, 7, CellConstraints.LEFT, CellConstraints.FILL));
        saveButton = new JButton();
        saveButton.setText("Salva");
        detailPanel.add(saveButton, cc.xy(1, 12));
        cancelButton = new JButton();
        cancelButton.setText("Annulla");
        detailPanel.add(cancelButton, cc.xy(2, 12));
        registrationNumberField = new JTextField();
        registrationNumberField.setEditable(true);
        registrationNumberField.setPreferredSize(new Dimension(100, 30));
        detailPanel.add(registrationNumberField, cc.xy(2, 8, CellConstraints.FILL, CellConstraints.CENTER));
        registrationNumberLabel = new JLabel();
        registrationNumberLabel.setText("Num. Matricola");
        detailPanel.add(registrationNumberLabel, cc.xy(2, 7, CellConstraints.LEFT, CellConstraints.DEFAULT));
        residenceField = new JTextField();
        residenceField.setPreferredSize(new Dimension(150, 30));
        detailPanel.add(residenceField, cc.xyw(1, 10, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        residenceLabel = new JLabel();
        residenceLabel.setText("Residenza");
        detailPanel.add(residenceLabel, cc.xy(1, 9));
        final JSeparator separator1 = new JSeparator();
        detailPanel.add(separator1, cc.xyw(1, 11, 2, CellConstraints.FILL, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return detailPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        MaskFormatter dateFormatter = null;
        try {
            dateFormatter = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        dateFormatter.setPlaceholderCharacter('_');

        birthDateField = new JFormattedTextField(dateFormatter);
        birthDateField.setColumns(10);
    }
}